"""Export ROS2/MoveIt joint artifacts from the AppConfig — single source of truth.

The kinematic numbers that exist in both the CAN world and the ROS2 world
(joint names, soft limits, velocity/acceleration limits) live in
`config.yaml` / `backend/config.py`. To avoid those numbers drifting between
the two stacks we generate the ROS2-side YAML from the same `AppConfig`
instead of hand-authoring it.

This module is pure Python with no ROS dependency so it can run anywhere
(CI, the laptop, a build step) and be unit-tested like the rest of `backend/`.

Two artifacts are produced:

  arctos_joints.yaml   consumed by the xacro (via xacro `load_yaml`) so the
                       URDF joint <limit> tags and the <ros2_control> block
                       both derive from the config. Angles in radians.

  joint_limits.yaml    MoveIt's joint_limits format (velocity/acceleration).

Regenerate whenever `config.yaml` changes:

    python -m backend.ros_export --config config.yaml --out \\
        ros2_ws/src/arctos_description/config/
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path

import yaml

from .config import AppConfig, AxisConfig

# Joints are revolute; effort limits are not modelled by the MKS layer, so we
# emit a nominal value the planner is happy with. Tune per robot if needed.
DEFAULT_EFFORT = 100.0


def _joint_entry(ax: AxisConfig) -> dict:
    """One joint's kinematic + limit data, angles in radians."""
    return {
        "can_id": ax.can_id,
        "lower": round(math.radians(ax.soft_limit_min), 6),
        "upper": round(math.radians(ax.soft_limit_max), 6),
        "velocity": round(math.radians(ax.max_vel_deg_s), 6),
        "acceleration": round(math.radians(ax.max_acc_deg_s2), 6),
        "effort": DEFAULT_EFFORT,
    }


def joints_spec(cfg: AppConfig) -> dict:
    """Full joint spec for the URDF/ros2_control xacro (load_yaml input)."""
    return {
        "robot_type": cfg.robot_type,
        "joints": {ax.name: _joint_entry(ax) for ax in cfg.axes},
    }


def joint_limits(cfg: AppConfig) -> dict:
    """MoveIt `joint_limits.yaml` content (velocity + acceleration)."""
    limits = {}
    for ax in cfg.axes:
        limits[ax.name] = {
            "has_velocity_limits": True,
            "max_velocity": round(math.radians(ax.max_vel_deg_s), 6),
            "has_acceleration_limits": True,
            "max_acceleration": round(math.radians(ax.max_acc_deg_s2), 6),
        }
    return {"joint_limits": limits}


_AUTOGEN_HEADER = (
    "# AUTO-GENERATED by `python -m backend.ros_export` — DO NOT EDIT BY HAND.\n"
    "# Source of truth is config.yaml / backend/config.py. Regenerate after edits.\n"
)


def _dump(data: dict) -> str:
    return _AUTOGEN_HEADER + yaml.safe_dump(data, sort_keys=False, default_flow_style=False)


def write_artifacts(cfg: AppConfig, out_dir: Path) -> list[Path]:
    """Write arctos_joints.yaml + joint_limits.yaml into out_dir. Returns paths."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, data in (
        ("arctos_joints.yaml", joints_spec(cfg)),
        ("joint_limits.yaml", joint_limits(cfg)),
    ):
        path = out_dir / name
        path.write_text(_dump(data))
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("config.yaml"),
        help="Path to config.yaml (falls back to built-in 6-axis defaults if missing).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        required=True,
        help="Output directory for the generated YAML files.",
    )
    args = parser.parse_args(argv)

    cfg = AppConfig.load(args.config)
    written = write_artifacts(cfg, args.out)
    for path in written:
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
